---
driver:
    name: vagrant

provisioner:
#  ansible_platform: ubuntu
  name: ansible_playbook
#  roles_path:
  hosts: test-kitchen
  require_ansible_omnibus: true
  ansible_omnibus_url: http://10.0.2.2:8080/install_ansible.sh
#  require_ansible_repo: true
  require_ruby_for_busser: false
  require_chef_for_busser: true
#  ansible_check: true
  ansible_diff: true
  ansible_verbose: true
  ansible_verbosity: 2
  sudo: true
  # playbook: default.yml
  extra_vars:
    rp_environment: dev

platforms:
  #- name: ubuntu-10.04 # lucid
  #- name: ubuntu-12.04 # precise
  #- name: ubuntu-13.10 # saucy
  #- name: ubuntu-14.04 # trusty
  # - name: ubuntu-14.10 # utopic ## No bento box yet... Official Scheduled Release: October 23rd 2014
  # - name: centos-5.10 # TODO: NOT TESTED YET... unsure if kitchen-ansible works yet...
  - name: centos-6.4
  - name: centos-6.5
  - name: centos-7.0
  # - name: nocm_centos-6.5
  #   driver_plugin: vagrant
  #   driver_config:
  #     box: nocm_centos-6.5
  #     box_url: http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-nocm.box
      # network:
      #  - ['forwarded_port', {guest: 8080, host: 8080}]
      #  - [ 'private_network', { ip: '192.168.33.11' } ]

suites:
  - name: default
  - name: daemon
    provisioner:
      playbook: test/integration/daemon.yml
      extra_vars:
        # Vars for testing the role in test-kitchen
        rsync_install_daemon: true
        rsync_daemon_shares:
          kitchen:
            path: /tmp/kitchen/
            comment: test-kitchen
            uid: vagrant
            gid: vagrant
            read only: "no"
            list: "yes"
            auth users: vagrant, kitchen
            secrets file: /etc/rsyncd.secrets
            hosts allow: 127.0.0.1/255.255.255.0
        # Normally these vars would be in Ansible Vault
        rsync_daemon_user_secrets:
          vagrant: vagrant
          kitchen: kitchen
# - name: my-suite
#   provisioner:
#     extra_vars:
#       foo: bar
